apiVersion : apps/v1
kind: Deployment
metadata:
  name: gcodevopsteamcapstoneapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcodevopsteamcapstoneapi
  template:
    metadata:
      labels:
        app: gcodevopsteamcapstoneapi 
    spec:
      containers:
        - name: gcodevopsteamcapstoneapi 
          image: gcodevopsteamcapstoneacr.azurecr.io/gcodevopsteamcapstoneapi
          ports:
          - containerPort: 80